import dynamic from "next/dynamic";
import Head from "next/head";

const LandingPageNoSSR = dynamic(
  () => import('../components/LandingPage/LandingPage'),
  { ssr: false }
);

export default function Home() {
  return (
    <>
      <Head>
        <title>Guinwa Khaddaj</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LandingPageNoSSR />

    </>
  );
}
